server:
  port: 8080

spring:
  application:
    name: test-mail
  mail:
    host: smtp.qq.com
    username: 804236345@qq.com
    password: vvvwjaojqllpbbbh
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
